In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,f1_score,precision_score

In [7]:
import warnings
warnings.filterwarnings('ignore')

In [8]:
df=pd.read_csv('data/diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [9]:
X=df.drop(columns=['Outcome'],axis=1)
y=df['Outcome']

In [10]:
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

In [11]:
num_feature=X.select_dtypes(exclude='object').columns
len(num_feature)

8

In [12]:
numeric_transfrom=StandardScaler()
preprocessor=ColumnTransformer(
    [
        ('StandardScaler',numeric_transfrom,num_feature)
    ],remainder='passthrough'
)

In [13]:
X=preprocessor.fit_transform(X)

In [14]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7
0,0.639947,0.848324,0.149641,0.907270,-0.692891,0.204013,0.468492,1.425995
1,-0.844885,-1.123396,-0.160546,0.530902,-0.692891,-0.684422,-0.365061,-0.190672
2,1.233880,1.943724,-0.263941,-1.288212,-0.692891,-1.103255,0.604397,-0.105584
3,-0.844885,-0.998208,-0.160546,0.154533,0.123302,-0.494043,-0.920763,-1.041549
4,-1.141852,0.504055,-1.504687,0.907270,0.765836,1.409746,5.484909,-0.020496
...,...,...,...,...,...,...,...,...
763,1.827813,-0.622642,0.356432,1.722735,0.870031,0.115169,-0.908682,2.532136
764,-0.547919,0.034598,0.046245,0.405445,-0.692891,0.610154,-0.398282,-0.531023
765,0.342981,0.003301,0.149641,0.154533,0.279594,-0.735190,-0.685193,-0.275760
766,-0.844885,0.159787,-0.470732,-1.288212,-0.692891,-0.240205,-0.371101,1.170732
767,-0.844885,-0.873019,0.046245,0.656358,-0.692891,-0.202129,-0.473785,-0.871374

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [16]:
X_train.shape,X_test.shape

((576, 8), (192, 8))

In [17]:
def evaluate_model(true,pred):
    accuracy=accuracy_score(true,pred)
    f1score=f1_score(true,pred)
    pscore=precision_score(true,pred)
    
    return accuracy,f1score,pscore

In [18]:
models={
    'LogisticRegression':LogisticRegression(),
    'DecisionTreeClassifier':DecisionTreeClassifier(),
    'RandomForestClassifier':RandomForestClassifier(),
    'AdaBoostClassifier':AdaBoostClassifier(),
    'GradientBoostingClassifier':GradientBoostingClassifier(),
    'SVC':SVC(),
    'CatBoostClassifier':CatBoostClassifier(),
    'XGBClassifier':XGBClassifier()
}
model_list=[]
accuray_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)
    
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)
    
    y_train_acc,y_train_f1,y_train_pre=evaluate_model(y_train,y_train_pred)
    y_test_acc,y_test_f1,y_test_pre=evaluate_model(y_test,y_test_pred)
    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    accuray_list.append(y_test_acc)
    
    print("Train performance")
    print('accuracy score:{:.4f}'.format(y_train_acc))
    print('f1 score:{:.4f}'.format(y_train_f1))
    print('precission score :{:.4f}'.format(y_train_pre))
    
    print('\n')
    
    print("Test performance:")
    print('accuracy score:{:.4f}'.format(y_test_acc))
    print('f1 score:{:.4f}'.format(y_test_f1))
    print('precission score:{:.4f}'.format(y_test_pre))

LogisticRegression
Train performance
accuracy score:0.7795
f1 score:0.6402
precission score :0.7338


Test performance:
accuracy score:0.7292
f1 score:0.6338
precission score:0.6164
DecisionTreeClassifier
Train performance
accuracy score:1.0000
f1 score:1.0000
precission score :1.0000


Test performance:
accuracy score:0.6979
f1 score:0.6184
precission score:0.5663
RandomForestClassifier
Train performance
accuracy score:1.0000
f1 score:1.0000
precission score :1.0000


Test performance:
accuracy score:0.7240
f1 score:0.6074
precission score:0.6212
AdaBoostClassifier
Train performance
accuracy score:0.7934
f1 score:0.6810
precission score :0.7299


Test performance:
accuracy score:0.7344
f1 score:0.6383
precission score:0.6250
GradientBoostingClassifier
Train performance
accuracy score:0.9410
f1 score:0.9105
precission score :0.9558


Test performance:
accuracy score:0.7500
f1 score:0.6667
precission score:0.6400
SVC
Train performance
accuracy score:0.8316
f1 score:0.7313
precission score :0.8148


Test performance:
accuracy score:0.7292
f1 score:0.6000
precission score:0.6393
Learning rate set to 0.00814
0:	learn: 0.6887270	total: 52.4ms	remaining: 52.3s
1:	learn: 0.6850056	total: 53.4ms	remaining: 26.6s
2:	learn: 0.6811532	total: 54.3ms	remaining: 18s
3:	learn: 0.6767381	total: 55.1ms	remaining: 13.7s
4:	learn: 0.6719693	total: 56ms	remaining: 11.1s
5:	learn: 0.6678811	total: 57.2ms	remaining: 9.47s
6:	learn: 0.6636459	total: 58.1ms	remaining: 8.24s
7:	learn: 0.6597433	total: 59ms	remaining: 7.32s
8:	learn: 0.6559192	total: 59.9ms	remaining: 6.6s
9:	learn: 0.6520927	total: 61ms	remaining: 6.04s
10:	learn: 0.6476542	total: 61.9ms	remaining: 5.56s
11:	learn: 0.6446328	total: 62.7ms	remaining: 5.16s
12:	learn: 0.6409383	total: 63.5ms	remaining: 4.82s
13:	learn: 0.6373277	total: 64.4ms	remaining: 4.53s
14:	learn: 0.6336530	total: 65.1ms	remaining: 4.28s
15:	learn: 0.6304582	total: 65.9ms	remaining: 4.05s
16:	learn: 0.6268786	total: 66.7ms	remaining: 3.86s
17:	learn: 0.6238468	total: 67.4ms	remaining: 3.68s
18:	learn: 0.6209246	total: 68ms	remaining: 3.51s
19:	learn: 0.6184045	total: 68.7ms	remaining: 3.37s
20:	learn: 0.6147575	total: 69.3ms	remaining: 3.23s
21:	learn: 0.6118262	total: 70ms	remaining: 3.11s
22:	learn: 0.6092090	total: 70.6ms	remaining: 3s
23:	learn: 0.6053126	total: 71.4ms	remaining: 2.9s
24:	learn: 0.6020266	total: 72.1ms	remaining: 2.81s
25:	learn: 0.5995039	total: 72.7ms	remaining: 2.73s
26:	learn: 0.5963221	total: 73.4ms	remaining: 2.64s
27:	learn: 0.5933983	total: 74ms	remaining: 2.57s
28:	learn: 0.5902294	total: 74.8ms	remaining: 2.5s
29:	learn: 0.5867653	total: 75.4ms	remaining: 2.44s
30:	learn: 0.5830754	total: 76.1ms	remaining: 2.38s
31:	learn: 0.5802135	total: 76.8ms	remaining: 2.32s
32:	learn: 0.5774693	total: 77.5ms	remaining: 2.27s
33:	learn: 0.5755033	total: 78.1ms	remaining: 2.22s
34:	learn: 0.5731364	total: 78.9ms	remaining: 2.18s
35:	learn: 0.5705097	total: 79.6ms	remaining: 2.13s
36:	learn: 0.5678044	total: 80.2ms	remaining: 2.09s
37:	learn: 0.5654102	total: 80.9ms	remaining: 2.05s
38:	learn: 0.5626721	total: 81.5ms	remaining: 2.01s
39:	learn: 0.5601707	total: 82.1ms	remaining: 1.97s
40:	learn: 0.5574119	total: 82.7ms	remaining: 1.93s
41:	learn: 0.5550016	total: 83.3ms	remaining: 1.9s
42:	learn: 0.5523530	total: 84ms	remaining: 1.87s
43:	learn: 0.5500930	total: 84.6ms	remaining: 1.84s
44:	learn: 0.5478291	total: 85.2ms	remaining: 1.81s
45:	learn: 0.5454913	total: 86ms	remaining: 1.78s
46:	learn: 0.5438144	total: 86.7ms	remaining: 1.76s
47:	learn: 0.5417175	total: 87.4ms	remaining: 1.73s
48:	learn: 0.5392065	total: 88ms	remaining: 1.71s
49:	learn: 0.5370131	total: 88.6ms	remaining: 1.68s
50:	learn: 0.5348304	total: 89.2ms	remaining: 1.66s
51:	learn: 0.5331077	total: 90.2ms	remaining: 1.65s
52:	learn: 0.5304599	total: 90.9ms	remaining: 1.62s
53:	learn: 0.5287204	total: 91.6ms	remaining: 1.6s
54:	learn: 0.5266396	total: 92.3ms	remaining: 1.58s
55:	learn: 0.5243897	total: 93ms	remaining: 1.57s
56:	learn: 0.5225577	total: 93.8ms	remaining: 1.55s
57:	learn: 0.5207485	total: 94.5ms	remaining: 1.53s
58:	learn: 0.5183406	total: 95.1ms	remaining: 1.52s
59:	learn: 0.5163709	total: 95.7ms	remaining: 1.5s
60:	learn: 0.5145657	total: 96.3ms	remaining: 1.48s
61:	learn: 0.5132243	total: 97ms	remaining: 1.47s
62:	learn: 0.5118367	total: 97.6ms	remaining: 1.45s
63:	learn: 0.5100919	total: 98.2ms	remaining: 1.44s
64:	learn: 0.5081369	total: 98.8ms	remaining: 1.42s
65:	learn: 0.5065752	total: 99.5ms	remaining: 1.41s
66:	learn: 0.5045751	total: 100ms	remaining: 1.4s
67:	learn: 0.5028205	total: 101ms	remaining: 1.38s
68:	learn: 0.5020850	total: 101ms	remaining: 1.37s
69:	learn: 0.5008102	total: 102ms	remaining: 1.35s
70:	learn: 0.4993591	total: 103ms	remaining: 1.34s
71:	learn: 0.4977481	total: 103ms	remaining: 1.33s
72:	learn: 0.4961598	total: 104ms	remaining: 1.32s
73:	learn: 0.4944304	total: 105ms	remaining: 1.31s
74:	learn: 0.4926279	total: 106ms	remaining: 1.3s
75:	learn: 0.4911152	total: 107ms	remaining: 1.29s
76:	learn: 0.4893400	total: 107ms	remaining: 1.29s
77:	learn: 0.4877498	total: 108ms	remaining: 1.28s
78:	learn: 0.4863860	total: 109ms	remaining: 1.27s
79:	learn: 0.4851191	total: 109ms	remaining: 1.26s
80:	learn: 0.4838416	total: 110ms	remaining: 1.25s
81:	learn: 0.4819423	total: 111ms	remaining: 1.24s
82:	learn: 0.4806049	total: 112ms	remaining: 1.23s
83:	learn: 0.4792440	total: 113ms	remaining: 1.23s
84:	learn: 0.4779097	total: 113ms	remaining: 1.22s
85:	learn: 0.4765760	total: 114ms	remaining: 1.21s
86:	learn: 0.4756083	total: 115ms	remaining: 1.21s
87:	learn: 0.4744613	total: 116ms	remaining: 1.2s
88:	learn: 0.4729806	total: 116ms	remaining: 1.19s
89:	learn: 0.4717176	total: 117ms	remaining: 1.18s
90:	learn: 0.4702079	total: 118ms	remaining: 1.18s
91:	learn: 0.4687370	total: 119ms	remaining: 1.17s
92:	learn: 0.4672780	total: 120ms	remaining: 1.17s
93:	learn: 0.4663995	total: 120ms	remaining: 1.16s
94:	learn: 0.4650292	total: 121ms	remaining: 1.15s
95:	learn: 0.4637233	total: 122ms	remaining: 1.15s
96:	learn: 0.4624145	total: 122ms	remaining: 1.14s
97:	learn: 0.4610322	total: 123ms	remaining: 1.13s
98:	learn: 0.4598393	total: 124ms	remaining: 1.13s
99:	learn: 0.4588198	total: 125ms	remaining: 1.12s
100:	learn: 0.4578483	total: 125ms	remaining: 1.11s
101:	learn: 0.4566947	total: 126ms	remaining: 1.11s
102:	learn: 0.4556510	total: 127ms	remaining: 1.11s
103:	learn: 0.4544504	total: 128ms	remaining: 1.1s
104:	learn: 0.4531391	total: 129ms	remaining: 1.1s
105:	learn: 0.4518158	total: 130ms	remaining: 1.1s
106:	learn: 0.4507742	total: 131ms	remaining: 1.09s
107:	learn: 0.4499665	total: 132ms	remaining: 1.09s
108:	learn: 0.4487665	total: 132ms	remaining: 1.08s
109:	learn: 0.4478535	total: 135ms	remaining: 1.09s
110:	learn: 0.4466021	total: 140ms	remaining: 1.12s
111:	learn: 0.4459276	total: 143ms	remaining: 1.13s
112:	learn: 0.4451246	total: 144ms	remaining: 1.13s
113:	learn: 0.4438672	total: 146ms	remaining: 1.13s
114:	learn: 0.4430380	total: 146ms	remaining: 1.13s
115:	learn: 0.4422661	total: 148ms	remaining: 1.13s
116:	learn: 0.4412561	total: 149ms	remaining: 1.12s
117:	learn: 0.4399632	total: 151ms	remaining: 1.13s
118:	learn: 0.4388317	total: 153ms	remaining: 1.13s
119:	learn: 0.4380477	total: 154ms	remaining: 1.13s
120:	learn: 0.4375054	total: 156ms	remaining: 1.13s
121:	learn: 0.4366784	total: 158ms	remaining: 1.14s
122:	learn: 0.4361015	total: 159ms	remaining: 1.13s
123:	learn: 0.4350633	total: 160ms	remaining: 1.13s
124:	learn: 0.4342393	total: 161ms	remaining: 1.13s
125:	learn: 0.4334061	total: 162ms	remaining: 1.12s
126:	learn: 0.4326755	total: 163ms	remaining: 1.12s
127:	learn: 0.4318632	total: 164ms	remaining: 1.12s
128:	learn: 0.4309307	total: 165ms	remaining: 1.12s
129:	learn: 0.4302368	total: 166ms	remaining: 1.11s
130:	learn: 0.4295617	total: 168ms	remaining: 1.11s
131:	learn: 0.4288133	total: 169ms	remaining: 1.11s
132:	learn: 0.4281289	total: 171ms	remaining: 1.11s
133:	learn: 0.4272166	total: 172ms	remaining: 1.11s
134:	learn: 0.4264117	total: 173ms	remaining: 1.11s
135:	learn: 0.4257201	total: 174ms	remaining: 1.1s
136:	learn: 0.4249347	total: 175ms	remaining: 1.1s
137:	learn: 0.4242464	total: 176ms	remaining: 1.1s
138:	learn: 0.4233874	total: 177ms	remaining: 1.09s
139:	learn: 0.4225742	total: 177ms	remaining: 1.09s
140:	learn: 0.4217799	total: 178ms	remaining: 1.08s
141:	learn: 0.4208360	total: 179ms	remaining: 1.08s
142:	learn: 0.4202585	total: 180ms	remaining: 1.08s
143:	learn: 0.4197163	total: 181ms	remaining: 1.07s
144:	learn: 0.4191390	total: 182ms	remaining: 1.07s
145:	learn: 0.4184795	total: 183ms	remaining: 1.07s
146:	learn: 0.4180482	total: 184ms	remaining: 1.06s
147:	learn: 0.4171056	total: 185ms	remaining: 1.06s
148:	learn: 0.4164560	total: 186ms	remaining: 1.06s
149:	learn: 0.4159652	total: 187ms	remaining: 1.06s
150:	learn: 0.4152021	total: 189ms	remaining: 1.06s
151:	learn: 0.4145793	total: 189ms	remaining: 1.06s
152:	learn: 0.4134747	total: 190ms	remaining: 1.05s
153:	learn: 0.4127421	total: 191ms	remaining: 1.05s
154:	learn: 0.4120666	total: 192ms	remaining: 1.04s
155:	learn: 0.4113939	total: 193ms	remaining: 1.04s
156:	learn: 0.4105385	total: 193ms	remaining: 1.04s
157:	learn: 0.4102063	total: 194ms	remaining: 1.03s
158:	learn: 0.4093010	total: 195ms	remaining: 1.03s
159:	learn: 0.4087033	total: 197ms	remaining: 1.03s
160:	learn: 0.4079791	total: 199ms	remaining: 1.03s
161:	learn: 0.4074506	total: 203ms	remaining: 1.05s
162:	learn: 0.4068125	total: 204ms	remaining: 1.05s
163:	learn: 0.4060602	total: 206ms	remaining: 1.05s
164:	learn: 0.4053766	total: 208ms	remaining: 1.05s
165:	learn: 0.4047919	total: 209ms	remaining: 1.05s
166:	learn: 0.4041739	total: 211ms	remaining: 1.05s
167:	learn: 0.4035072	total: 212ms	remaining: 1.05s
168:	learn: 0.4027577	total: 213ms	remaining: 1.05s
169:	learn: 0.4020531	total: 215ms	remaining: 1.05s
170:	learn: 0.4017272	total: 216ms	remaining: 1.05s
171:	learn: 0.4008716	total: 217ms	remaining: 1.04s
172:	learn: 0.4001187	total: 218ms	remaining: 1.04s
173:	learn: 0.3995704	total: 219ms	remaining: 1.04s
174:	learn: 0.3990015	total: 220ms	remaining: 1.04s
175:	learn: 0.3985744	total: 221ms	remaining: 1.03s
176:	learn: 0.3978187	total: 222ms	remaining: 1.03s
177:	learn: 0.3970972	total: 222ms	remaining: 1.03s
178:	learn: 0.3966031	total: 223ms	remaining: 1.02s
179:	learn: 0.3960672	total: 224ms	remaining: 1.02s
180:	learn: 0.3955857	total: 224ms	remaining: 1.01s
181:	learn: 0.3946872	total: 225ms	remaining: 1.01s
182:	learn: 0.3941303	total: 226ms	remaining: 1.01s
183:	learn: 0.3933256	total: 227ms	remaining: 1.01s
184:	learn: 0.3925753	total: 228ms	remaining: 1s
185:	learn: 0.3920904	total: 229ms	remaining: 1s
186:	learn: 0.3913216	total: 231ms	remaining: 1s
187:	learn: 0.3907453	total: 232ms	remaining: 1s
188:	learn: 0.3903133	total: 233ms	remaining: 999ms
189:	learn: 0.3896717	total: 235ms	remaining: 1s
190:	learn: 0.3888291	total: 238ms	remaining: 1.01s
191:	learn: 0.3881601	total: 239ms	remaining: 1.01s
192:	learn: 0.3876040	total: 241ms	remaining: 1.01s
193:	learn: 0.3870234	total: 242ms	remaining: 1.01s
194:	learn: 0.3864610	total: 243ms	remaining: 1s
195:	learn: 0.3860279	total: 245ms	remaining: 1s
196:	learn: 0.3854130	total: 246ms	remaining: 1s
197:	learn: 0.3849144	total: 248ms	remaining: 1s
198:	learn: 0.3843896	total: 250ms	remaining: 1s
199:	learn: 0.3837465	total: 252ms	remaining: 1.01s
200:	learn: 0.3832051	total: 253ms	remaining: 1.01s
201:	learn: 0.3824117	total: 255ms	remaining: 1.01s
202:	learn: 0.3821209	total: 256ms	remaining: 1s
203:	learn: 0.3816439	total: 257ms	remaining: 1s
204:	learn: 0.3812645	total: 258ms	remaining: 999ms
205:	learn: 0.3808257	total: 259ms	remaining: 997ms
206:	learn: 0.3800671	total: 259ms	remaining: 994ms
207:	learn: 0.3795471	total: 260ms	remaining: 991ms
208:	learn: 0.3790523	total: 261ms	remaining: 988ms
209:	learn: 0.3785512	total: 262ms	remaining: 986ms
210:	learn: 0.3780217	total: 263ms	remaining: 984ms
211:	learn: 0.3772470	total: 264ms	remaining: 981ms
212:	learn: 0.3766798	total: 265ms	remaining: 980ms
213:	learn: 0.3762585	total: 266ms	remaining: 977ms
214:	learn: 0.3756266	total: 267ms	remaining: 974ms
215:	learn: 0.3749444	total: 268ms	remaining: 971ms
216:	learn: 0.3744527	total: 269ms	remaining: 970ms
217:	learn: 0.3740550	total: 270ms	remaining: 969ms
218:	learn: 0.3736330	total: 271ms	remaining: 967ms
219:	learn: 0.3731080	total: 272ms	remaining: 966ms
220:	learn: 0.3726592	total: 273ms	remaining: 963ms
221:	learn: 0.3721652	total: 274ms	remaining: 961ms
222:	learn: 0.3717489	total: 275ms	remaining: 958ms
223:	learn: 0.3713498	total: 276ms	remaining: 956ms
224:	learn: 0.3709056	total: 277ms	remaining: 953ms
225:	learn: 0.3706311	total: 278ms	remaining: 951ms
226:	learn: 0.3700328	total: 279ms	remaining: 948ms
227:	learn: 0.3694000	total: 279ms	remaining: 946ms
228:	learn: 0.3688269	total: 281ms	remaining: 945ms
229:	learn: 0.3684475	total: 282ms	remaining: 943ms
230:	learn: 0.3679441	total: 282ms	remaining: 940ms
231:	learn: 0.3675401	total: 283ms	remaining: 938ms
232:	learn: 0.3670508	total: 285ms	remaining: 937ms
233:	learn: 0.3667479	total: 286ms	remaining: 937ms
234:	learn: 0.3661835	total: 288ms	remaining: 936ms
235:	learn: 0.3655544	total: 289ms	remaining: 936ms
236:	learn: 0.3651115	total: 291ms	remaining: 938ms
237:	learn: 0.3647778	total: 294ms	remaining: 940ms
238:	learn: 0.3643657	total: 295ms	remaining: 939ms
239:	learn: 0.3640643	total: 296ms	remaining: 937ms
240:	learn: 0.3636316	total: 297ms	remaining: 935ms
241:	learn: 0.3630653	total: 298ms	remaining: 932ms
242:	learn: 0.3626033	total: 299ms	remaining: 931ms
243:	learn: 0.3623841	total: 300ms	remaining: 930ms
244:	learn: 0.3620178	total: 301ms	remaining: 928ms
245:	learn: 0.3615796	total: 302ms	remaining: 926ms
246:	learn: 0.3610824	total: 303ms	remaining: 924ms
247:	learn: 0.3607532	total: 305ms	remaining: 924ms
248:	learn: 0.3601712	total: 306ms	remaining: 922ms
249:	learn: 0.3599008	total: 307ms	remaining: 920ms
250:	learn: 0.3594014	total: 308ms	remaining: 918ms
251:	learn: 0.3591592	total: 308ms	remaining: 915ms
252:	learn: 0.3588658	total: 309ms	remaining: 912ms
253:	learn: 0.3584789	total: 310ms	remaining: 909ms
254:	learn: 0.3580827	total: 310ms	remaining: 907ms
255:	learn: 0.3578009	total: 311ms	remaining: 904ms
256:	learn: 0.3574004	total: 312ms	remaining: 901ms
257:	learn: 0.3570879	total: 313ms	remaining: 900ms
258:	learn: 0.3564456	total: 314ms	remaining: 899ms
259:	learn: 0.3560469	total: 315ms	remaining: 898ms
260:	learn: 0.3555815	total: 316ms	remaining: 896ms
261:	learn: 0.3552358	total: 318ms	remaining: 895ms
262:	learn: 0.3550367	total: 319ms	remaining: 894ms
263:	learn: 0.3544973	total: 320ms	remaining: 892ms
264:	learn: 0.3541441	total: 321ms	remaining: 890ms
265:	learn: 0.3538712	total: 322ms	remaining: 888ms
266:	learn: 0.3535770	total: 322ms	remaining: 885ms
267:	learn: 0.3530785	total: 323ms	remaining: 883ms
268:	learn: 0.3524817	total: 325ms	remaining: 883ms
269:	learn: 0.3521302	total: 326ms	remaining: 881ms
270:	learn: 0.3518126	total: 327ms	remaining: 879ms
271:	learn: 0.3511550	total: 329ms	remaining: 879ms
272:	learn: 0.3506080	total: 330ms	remaining: 878ms
273:	learn: 0.3504376	total: 331ms	remaining: 878ms
274:	learn: 0.3502917	total: 333ms	remaining: 878ms
275:	learn: 0.3497781	total: 334ms	remaining: 877ms
276:	learn: 0.3493209	total: 336ms	remaining: 876ms
277:	learn: 0.3489535	total: 337ms	remaining: 875ms
278:	learn: 0.3486004	total: 338ms	remaining: 873ms
279:	learn: 0.3484466	total: 338ms	remaining: 870ms
280:	learn: 0.3480109	total: 339ms	remaining: 868ms
281:	learn: 0.3472731	total: 340ms	remaining: 865ms
282:	learn: 0.3465663	total: 340ms	remaining: 862ms
283:	learn: 0.3462186	total: 341ms	remaining: 860ms
284:	learn: 0.3459490	total: 342ms	remaining: 857ms
285:	learn: 0.3456008	total: 343ms	remaining: 856ms
286:	learn: 0.3451569	total: 344ms	remaining: 854ms
287:	learn: 0.3446422	total: 345ms	remaining: 853ms
288:	learn: 0.3443535	total: 346ms	remaining: 851ms
289:	learn: 0.3441946	total: 347ms	remaining: 849ms
290:	learn: 0.3438942	total: 348ms	remaining: 848ms
291:	learn: 0.3435824	total: 349ms	remaining: 847ms
292:	learn: 0.3430801	total: 350ms	remaining: 845ms
293:	learn: 0.3426433	total: 351ms	remaining: 843ms
294:	learn: 0.3423435	total: 352ms	remaining: 841ms
295:	learn: 0.3419247	total: 353ms	remaining: 838ms
296:	learn: 0.3416733	total: 353ms	remaining: 836ms
297:	learn: 0.3412389	total: 354ms	remaining: 834ms
298:	learn: 0.3409929	total: 354ms	remaining: 831ms
299:	learn: 0.3406838	total: 355ms	remaining: 829ms
300:	learn: 0.3404144	total: 356ms	remaining: 826ms
301:	learn: 0.3401016	total: 357ms	remaining: 824ms
302:	learn: 0.3399550	total: 358ms	remaining: 823ms
303:	learn: 0.3395395	total: 359ms	remaining: 821ms
304:	learn: 0.3393118	total: 360ms	remaining: 820ms
305:	learn: 0.3388294	total: 361ms	remaining: 819ms
306:	learn: 0.3385770	total: 362ms	remaining: 817ms
307:	learn: 0.3383375	total: 364ms	remaining: 817ms
308:	learn: 0.3379107	total: 365ms	remaining: 817ms
309:	learn: 0.3374373	total: 366ms	remaining: 815ms
310:	learn: 0.3372074	total: 367ms	remaining: 814ms
311:	learn: 0.3367602	total: 369ms	remaining: 813ms
312:	learn: 0.3363793	total: 370ms	remaining: 812ms
313:	learn: 0.3358579	total: 371ms	remaining: 811ms
314:	learn: 0.3355169	total: 372ms	remaining: 810ms
315:	learn: 0.3352869	total: 373ms	remaining: 808ms
316:	learn: 0.3350883	total: 374ms	remaining: 806ms
317:	learn: 0.3345932	total: 375ms	remaining: 804ms
318:	learn: 0.3344221	total: 376ms	remaining: 802ms
319:	learn: 0.3341460	total: 377ms	remaining: 800ms
320:	learn: 0.3338838	total: 378ms	remaining: 799ms
321:	learn: 0.3335092	total: 379ms	remaining: 798ms
322:	learn: 0.3332379	total: 380ms	remaining: 796ms
323:	learn: 0.3329798	total: 381ms	remaining: 794ms
324:	learn: 0.3324650	total: 381ms	remaining: 792ms
325:	learn: 0.3319325	total: 382ms	remaining: 790ms
326:	learn: 0.3316443	total: 383ms	remaining: 788ms
327:	learn: 0.3312740	total: 384ms	remaining: 786ms
328:	learn: 0.3309849	total: 385ms	remaining: 785ms
329:	learn: 0.3306841	total: 385ms	remaining: 783ms
330:	learn: 0.3303952	total: 386ms	remaining: 781ms
331:	learn: 0.3300255	total: 387ms	remaining: 778ms
332:	learn: 0.3297030	total: 388ms	remaining: 776ms
333:	learn: 0.3294045	total: 388ms	remaining: 774ms
334:	learn: 0.3290817	total: 389ms	remaining: 773ms
335:	learn: 0.3288100	total: 390ms	remaining: 771ms
336:	learn: 0.3285041	total: 391ms	remaining: 768ms
337:	learn: 0.3282736	total: 391ms	remaining: 766ms
338:	learn: 0.3280228	total: 392ms	remaining: 764ms
339:	learn: 0.3278678	total: 393ms	remaining: 762ms
340:	learn: 0.3275771	total: 393ms	remaining: 760ms
341:	learn: 0.3272318	total: 395ms	remaining: 759ms
342:	learn: 0.3268481	total: 395ms	remaining: 757ms
343:	learn: 0.3265970	total: 396ms	remaining: 755ms
344:	learn: 0.3263703	total: 397ms	remaining: 753ms
345:	learn: 0.3262919	total: 397ms	remaining: 751ms
346:	learn: 0.3260180	total: 398ms	remaining: 749ms
347:	learn: 0.3257406	total: 399ms	remaining: 747ms
348:	learn: 0.3255534	total: 399ms	remaining: 745ms
349:	learn: 0.3251707	total: 400ms	remaining: 743ms
350:	learn: 0.3248220	total: 401ms	remaining: 741ms
351:	learn: 0.3243901	total: 402ms	remaining: 739ms
352:	learn: 0.3242959	total: 403ms	remaining: 738ms
353:	learn: 0.3241936	total: 404ms	remaining: 738ms
354:	learn: 0.3237865	total: 405ms	remaining: 736ms
355:	learn: 0.3236003	total: 406ms	remaining: 734ms
356:	learn: 0.3233668	total: 407ms	remaining: 734ms
357:	learn: 0.3230027	total: 408ms	remaining: 732ms
358:	learn: 0.3226620	total: 409ms	remaining: 731ms
359:	learn: 0.3224590	total: 410ms	remaining: 729ms
360:	learn: 0.3220872	total: 411ms	remaining: 728ms
361:	learn: 0.3218827	total: 412ms	remaining: 726ms
362:	learn: 0.3216241	total: 413ms	remaining: 724ms
363:	learn: 0.3214429	total: 413ms	remaining: 722ms
364:	learn: 0.3211124	total: 414ms	remaining: 720ms

In [19]:
pd.DataFrame(list(zip(model_list,accuray_list)),columns=['model_name','accuracy']).sort_values(by=['accuracy'],ascending=False)

                   model_name  accuracy
4  GradientBoostingClassifier  0.750000
7               XGBClassifier  0.739583
3          AdaBoostClassifier  0.734375
0          LogisticRegression  0.729167
5                         SVC  0.729167
2      RandomForestClassifier  0.723958
6          CatBoostClassifier  0.723958
1      DecisionTreeClassifier  0.697917

In [20]:
grad_model=GradientBoostingClassifier()
grad_model.fit(X_train,y_train)
y_pred=grad_model.predict(X_test)
score=accuracy_score(y_test,y_pred)
print("Accuracy of the model is : %.2f", score)

Accuracy of the model is : %.2f 0.7447916666666666